-- MySQL Script generated by MySQL Workbench
-- Thu Nov  4 20:36:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema haruby
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema haruby
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `haruby` DEFAULT CHARACTER SET utf8 ;
USE `haruby` ;

-- -----------------------------------------------------
-- Table `haruby`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`User` (
                                               `user_idx` VARCHAR(30) NOT NULL,
                                               `user_name` VARCHAR(20) NULL,
                                               `user_email` VARCHAR(50) NULL,
                                               `user_phone` VARCHAR(20) NULL,
                                               `user_birthday` DATE NULL,
                                               `user_testresult` VARCHAR(50),
                                               `user_point` INT NULL,
                                               `user_create` DATE NULL,
                                               `user_logout` VARCHAR(1) NULL,
                                               `user_ordered` VARCHAR(45) NULL,
                                               PRIMARY KEY (`user_idx`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Deliver_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Deliver_address` (
                                                          `User_user_idx` VARCHAR(30) NOT NULL,
                                                          `user_address1` VARCHAR(45) NULL,
                                                          `user_address2` VARCHAR(45) NULL,
                                                          `user_address3` VARCHAR(45) NULL,
                                                          PRIMARY KEY (`User_user_idx`),
                                                          INDEX `fk_deliver_address_User_idx` (`User_user_idx` ASC) VISIBLE,
                                                          CONSTRAINT `fk_deliver_address_User`
                                                              FOREIGN KEY (`User_user_idx`)
                                                                  REFERENCES `haruby`.`User` (`user_idx`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Product_category` (
                                                           `category_code` VARCHAR(30) NOT NULL,
                                                           `category_name` VARCHAR(45) NULL,
                                                           PRIMARY KEY (`category_code`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Administer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Administer` (
                                                     `administer_id` INT NOT NULL,
                                                     `administer_name` VARCHAR(45) NULL,
                                                     PRIMARY KEY (`administer_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Seller` (
                                                 `seller_idx` INT NOT NULL AUTO_INCREMENT,
                                                 `seller_name` VARCHAR(45) NULL,
                                                 `seller_create` DATE NULL,
                                                 `seller_phone` VARCHAR(45) NULL,
                                                 PRIMARY KEY (`seller_idx`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Product` (
                                                  `product_idx` INT NOT NULL AUTO_INCREMENT,
                                                  `product_name` VARCHAR(45) NULL,
                                                  `product_contents(color/..)` LONGTEXT NULL,
                                                  `product_price` VARCHAR(45) NULL,
                                                  `product_stock` VARCHAR(45) NULL,
                                                  `product_image` VARCHAR(45) NULL,
                                                  `create_date` DATE NULL,
                                                  `product_hit` INT NULL,
                                                  `review_count` INT NULL,
                                                  `Product_category_category_code` VARCHAR(30) NOT NULL,
                                                  `Administer_administer_id` INT NOT NULL,
                                                  `Seller_seller_idx` INT NOT NULL,
                                                  PRIMARY KEY (`product_idx`, `Administer_administer_id`, `Seller_seller_idx`),
                                                  INDEX `fk_Product_Product_category1_idx` (`Product_category_category_code` ASC) VISIBLE,
                                                  INDEX `fk_Product_Administer1_idx` (`Administer_administer_id` ASC) VISIBLE,
                                                  INDEX `fk_Product_Seller1_idx` (`Seller_seller_idx` ASC) VISIBLE,
                                                  CONSTRAINT `fk_Product_Product_category1`
                                                      FOREIGN KEY (`Product_category_category_code`)
                                                          REFERENCES `haruby`.`Product_category` (`category_code`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_Product_Administer1`
                                                      FOREIGN KEY (`Administer_administer_id`)
                                                          REFERENCES `haruby`.`Administer` (`administer_id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_Product_Seller1`
                                                      FOREIGN KEY (`Seller_seller_idx`)
                                                          REFERENCES `haruby`.`Seller` (`seller_idx`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Order(주문/결제)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Order(주문/결제)` (
                                                       `order_idx` INT NOT NULL AUTO_INCREMENT,
                                                       `order_date` DATE NULL,
                                                       `receive_name` VARCHAR(45) NOT NULL,
                                                       `receive_phone` VARCHAR(45) NOT NULL,
                                                       `receive_email` VARCHAR(45) NOT NULL,
                                                       `address1` VARCHAR(45) NULL,
                                                       `address2` VARCHAR(45) NULL,
                                                       `address3` VARCHAR(45) NULL,
                                                       `refund_bank` VARCHAR(45) NULL,
                                                       `refund_account` VARCHAR(45) NULL,
                                                       `refund_name` VARCHAR(45) NULL,
                                                       `use_coupon` INT NULL,
                                                       `use_point` INT NULL,
                                                       `payment` VARCHAR(45) NULL,
                                                       `User_user_id` VARCHAR(30) NOT NULL,
                                                       PRIMARY KEY (`order_idx`, `User_user_id`),
                                                       INDEX `fk_Order(주문/결제)_User1_idx` (`User_user_id` ASC) VISIBLE,
                                                       CONSTRAINT `fk_Order(주문/결제)_User1`
                                                           FOREIGN KEY (`User_user_id`)
                                                               REFERENCES `haruby`.`User` (`user_idx`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Order_detail` (
                                                       `order_detail_idx` INT NOT NULL AUTO_INCREMENT,
                                                       `product_count` INT NULL,
                                                       `product_price` VARCHAR(45) NULL,
                                                       `product_status` VARCHAR(45) NULL,
                                                       `product_discount` VARCHAR(45) NULL,
                                                       `order_check` VARCHAR(1) NULL,
                                                       `Order(주문/결제)_order_number` INT NOT NULL,
                                                       PRIMARY KEY (`order_detail_idx`, `Order(주문/결제)_order_number`),
                                                       INDEX `fk_Order_detail_Order(주문/결제)1_idx` (`Order(주문/결제)_order_number` ASC) VISIBLE,
                                                       CONSTRAINT `fk_Order_detail_Order(주문/결제)1`
                                                           FOREIGN KEY (`Order(주문/결제)_order_number`)
                                                               REFERENCES `haruby`.`Order(주문/결제)` (`order_idx`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Order_refund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Order_refund` (
                                                       `refund_idx` INT NOT NULL AUTO_INCREMENT,
                                                       `refund_available` VARCHAR(1) NULL,
                                                       `refund_account` VARCHAR(45) NULL,
                                                       `refund_reason` VARCHAR(300) NULL,
                                                       `Order_order_number` INT NOT NULL,
                                                       PRIMARY KEY (`refund_idx`, `Order_order_number`),
                                                       INDEX `fk_Order_refund_Order1_idx` (`Order_order_number` ASC) VISIBLE,
                                                       CONSTRAINT `fk_Order_refund_Order1`
                                                           FOREIGN KEY (`Order_order_number`)
                                                               REFERENCES `haruby`.`Order(주문/결제)` (`order_idx`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Product_image` (
                                                        `image_idx` INT NOT NULL AUTO_INCREMENT,
                                                        `Product_product_number` INT NOT NULL,
                                                        `origin_file_name` VARCHAR(45) NULL,
                                                        `stored_file_name` VARCHAR(45) NULL,
                                                        `stored_thumbnail` VARCHAR(45) NULL,
                                                        `file_size` VARCHAR(45) NULL,
                                                        `file_date` VARCHAR(45) NULL,
                                                        PRIMARY KEY (`image_idx`),
                                                        INDEX `fk_Product_image_Product1_idx` (`Product_product_number` ASC) VISIBLE,
                                                        CONSTRAINT `fk_Product_image_Product1`
                                                            FOREIGN KEY (`Product_product_number`)
                                                                REFERENCES `haruby`.`Product` (`product_idx`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Cart(장바구니)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Cart(장바구니)` (
                                                     `cart_idx` INT NOT NULL AUTO_INCREMENT,
                                                     `product_count` VARCHAR(45) NULL,
                                                     `product_delete` VARCHAR(1) NULL,
                                                     `product_change` VARCHAR(1) NULL,
                                                     `product_discount` VARCHAR(45) NULL,
                                                     `product_totalprice` VARCHAR(45) NULL,
                                                     `deliveryfee` VARCHAR(45) NULL,
                                                     `after_point` VARCHAR(45) NULL,
                                                     `Product_product_number` INT NOT NULL,
                                                     PRIMARY KEY (`cart_idx`, `Product_product_number`),
                                                     INDEX `fk_Cart(장바구니)_Product1_idx` (`Product_product_number` ASC) VISIBLE,
                                                     CONSTRAINT `fk_Cart(장바구니)_Product1`
                                                         FOREIGN KEY (`Product_product_number`)
                                                             REFERENCES `haruby`.`Product` (`product_idx`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Store` (
                                                `store_idx` INT NOT NULL AUTO_INCREMENT,
                                                `store_name` VARCHAR(45) NULL,
                                                `store_image` VARCHAR(45) NULL,
                                                `Product_product_number` INT NOT NULL,
                                                `store_hashtag` VARCHAR(45),
                                                PRIMARY KEY (`store_idx`, `Product_product_number`),
                                                INDEX `fk_Store_Product1_idx` (`Product_product_number` ASC) VISIBLE,
                                                CONSTRAINT `fk_Store_Product1`
                                                    FOREIGN KEY (`Product_product_number`)
                                                        REFERENCES `haruby`.`Product` (`product_idx`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Preference` (
                                                     `preference_idx` INT NOT NULL AUTO_INCREMENT,
                                                     `preference_` VARCHAR(45) NULL,
                                                     `preference_image` VARCHAR(45) NULL,
                                                     `User_user_id` VARCHAR(30) NOT NULL,
                                                     `folder_` VARCHAR(45) NULL,
                                                     `folder_name` VARCHAR(45) NULL,
                                                     `preference_store` VARCHAR(45) NULL,
                                                     `Product_product_number` INT NOT NULL,
                                                     `Product_Administer_administer_id` INT NOT NULL,
                                                     `Store_store_id` INT NOT NULL,
                                                     `Store_Product_product_number` INT NOT NULL,
                                                     PRIMARY KEY (`preference_idx`, `User_user_id`, `Product_product_number`, `Product_Administer_administer_id`, `Store_store_id`, `Store_Product_product_number`),
                                                     INDEX `fk_Preference_User1_idx` (`User_user_id` ASC) VISIBLE,
                                                     INDEX `fk_Preference_Product1_idx` (`Product_product_number` ASC, `Product_Administer_administer_id` ASC) VISIBLE,
                                                     INDEX `fk_Preference_Store1_idx` (`Store_store_id` ASC, `Store_Product_product_number` ASC) VISIBLE,
                                                     CONSTRAINT `fk_Preference_User1`
                                                         FOREIGN KEY (`User_user_id`)
                                                             REFERENCES `haruby`.`User` (`user_idx`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_Preference_Product1`
                                                         FOREIGN KEY (`Product_product_number` , `Product_Administer_administer_id`)
                                                             REFERENCES `haruby`.`Product` (`product_idx` , `Administer_administer_id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_Preference_Store1`
                                                         FOREIGN KEY (`Store_store_id` , `Store_Product_product_number`)
                                                             REFERENCES `haruby`.`Store` (`store_idx` , `Product_product_number`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Curation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Curation` (
                                                   `curation_idx` INT NOT NULL AUTO_INCREMENT,
                                                   `curation_image` VARCHAR(45) NULL,
                                                   `curation_title` VARCHAR(45) NULL,
                                                   `curation_content` VARCHAR(45) NULL,
                                                   `curation_tag` VARCHAR(45) NULL,
                                                   `Administer_administer_id` INT NOT NULL,
                                                   PRIMARY KEY (`curation_idx`, `Administer_administer_id`),
                                                   INDEX `fk_Curation_Administer1_idx` (`Administer_administer_id` ASC) VISIBLE,
                                                   CONSTRAINT `fk_Curation_Administer1`
                                                       FOREIGN KEY (`Administer_administer_id`)
                                                           REFERENCES `haruby`.`Administer` (`administer_id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Coupon` (
                                                 `coupon_idx` INT NOT NULL AUTO_INCREMENT,
                                                 `coupon_name` VARCHAR(45) NULL,
                                                 `coupon_content` VARCHAR(45) NULL,
                                                 `User_user_id` VARCHAR(30) NOT NULL,
                                                 PRIMARY KEY (`coupon_idx`, `User_user_id`),
                                                 INDEX `fk_Coupon_User1_idx` (`User_user_id` ASC) VISIBLE,
                                                 CONSTRAINT `fk_Coupon_User1`
                                                     FOREIGN KEY (`User_user_id`)
                                                         REFERENCES `haruby`.`User` (`user_idx`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Review` (
                                                 `review_idx` INT NOT NULL AUTO_INCREMENT,
                                                 `review_title` VARCHAR(45) NULL,
                                                 `review_content` VARCHAR(45) NULL,
                                                 `review_image` VARCHAR(45) NULL,
                                                 `review_date` VARCHAR(45) NULL,
                                                 `Product_product_number` INT NOT NULL,
                                                 `User_user_id` VARCHAR(30) NOT NULL,
                                                 PRIMARY KEY (`review_idx`, `Product_product_number`, `User_user_id`),
                                                 INDEX `fk_Review_Product1_idx` (`Product_product_number` ASC) VISIBLE,
                                                 INDEX `fk_Review_User1_idx` (`User_user_id` ASC) VISIBLE,
                                                 CONSTRAINT `fk_Review_Product1`
                                                     FOREIGN KEY (`Product_product_number`)
                                                         REFERENCES `haruby`.`Product` (`product_idx`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION,
                                                 CONSTRAINT `fk_Review_User1`
                                                     FOREIGN KEY (`User_user_id`)
                                                         REFERENCES `haruby`.`User` (`user_idx`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`FAQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`FAQ` (
                                              `faq_idx` INT NOT NULL AUTO_INCREMENT,
                                              `faq_title` VARCHAR(50) NULL,
                                              `faq_content` LONGTEXT NULL,
                                              `CustomerService_cs_number` INT NOT NULL,
                                              `User_user_id` VARCHAR(30) NOT NULL,
                                              `Administer_administer_id` INT NOT NULL,
                                              PRIMARY KEY (`faq_idx`, `CustomerService_cs_number`, `Administer_administer_id`),
                                              INDEX `fk_FAQ_User1_idx` (`User_user_id` ASC) VISIBLE,
                                              INDEX `fk_FAQ_Administer1_idx` (`Administer_administer_id` ASC) VISIBLE,
                                              CONSTRAINT `fk_FAQ_User1`
                                                  FOREIGN KEY (`User_user_id`)
                                                      REFERENCES `haruby`.`User` (`user_idx`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                              CONSTRAINT `fk_FAQ_Administer1`
                                                  FOREIGN KEY (`Administer_administer_id`)
                                                      REFERENCES `haruby`.`Administer` (`administer_id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Alert` (
                                                `alert_idx` INT NOT NULL AUTO_INCREMENT,
                                                `alert_push` VARCHAR(1) NULL,
                                                `alert_sms` VARCHAR(1) NULL,
                                                `alert_email` VARCHAR(1) NULL,
                                                `User_user_id` VARCHAR(30) NOT NULL,
                                                PRIMARY KEY (`alert_idx`),
                                                INDEX `fk_Alert_User1_idx` (`User_user_id` ASC) VISIBLE,
                                                CONSTRAINT `fk_Alert_User1`
                                                    FOREIGN KEY (`User_user_id`)
                                                        REFERENCES `haruby`.`User` (`user_idx`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Notice` (
                                                 `notice_idx` INT NOT NULL AUTO_INCREMENT,
                                                 `notice_title` VARCHAR(45) NULL,
                                                 `notice_content` LONGTEXT NULL,
                                                 `User_user_id` VARCHAR(30) NOT NULL,
                                                 `Administer_administer_id` INT NOT NULL,
                                                 PRIMARY KEY (`notice_idx`, `Administer_administer_id`),
                                                 INDEX `fk_Notice_User1_idx` (`User_user_id` ASC) VISIBLE,
                                                 INDEX `fk_Notice_Administer1_idx` (`Administer_administer_id` ASC) VISIBLE,
                                                 CONSTRAINT `fk_Notice_User1`
                                                     FOREIGN KEY (`User_user_id`)
                                                         REFERENCES `haruby`.`User` (`user_idx`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION,
                                                 CONSTRAINT `fk_Notice_Administer1`
                                                     FOREIGN KEY (`Administer_administer_id`)
                                                         REFERENCES `haruby`.`Administer` (`administer_id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haruby`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Request` (
                                                  `request_idx` INT NOT NULL AUTO_INCREMENT,
                                                  `request_title` VARCHAR(45) NULL,
                                                  `request_content` LONGTEXT NULL,
                                                  `CustomerService_cs_number` INT NOT NULL,
                                                  `User_user_id` VARCHAR(30) NOT NULL,
                                                  `request_answer` LONGTEXT NULL,
                                                  `Administer_administer_id` INT NOT NULL,
                                                  PRIMARY KEY (`request_idx`, `CustomerService_cs_number`, `User_user_id`),
                                                  INDEX `fk_Request_User1_idx` (`User_user_id` ASC) VISIBLE,
                                                  INDEX `fk_Request_Administer1_idx` (`Administer_administer_id` ASC) VISIBLE,
                                                  CONSTRAINT `fk_Request_User1`
                                                      FOREIGN KEY (`User_user_id`)
                                                          REFERENCES `haruby`.`User` (`user_idx`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_Request_Administer1`
                                                      FOREIGN KEY (`Administer_administer_id`)
                                                          REFERENCES `haruby`.`Administer` (`administer_id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `haruby`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haruby`.`Payment` (
                                                  `Order(주문/결제)_order_number` INT NOT NULL,
                                                  `Order(주문/결제)_User_user_id` VARCHAR(30) NOT NULL,
                                                  `payment_name` VARCHAR(45) NULL,
                                                  PRIMARY KEY (`Order(주문/결제)_order_number`, `Order(주문/결제)_User_user_id`),
                                                  CONSTRAINT `fk_Payment_Order(주문/결제)1`
                                                      FOREIGN KEY (`Order(주문/결제)_order_number` , `Order(주문/결제)_User_user_id`)
                                                          REFERENCES `haruby`.`Order(주문/결제)` (`order_idx` , `User_user_id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
